"use strict";

/**
 * Capability index access + the security validation gate for the GENERIC
 * `catalog` and `dynamic` operations.
 *
 * The capability index (srv/a2a/catalog-index.json) is a build-time snapshot of
 * the curated SAP OData catalog: services -> entity sets -> {keys, properties}.
 * It is generated by scripts/gen-skills.js from the curated catalog.
 *
 * TWO responsibilities:
 *   1. VIEWS (operation 'catalog', LOCAL, no backend call): listServices,
 *      describeService, describeEntitySet — return schema/help so the Copilot
 *      Studio LLM learns exact service/entity-set/field names.
 *   2. VALIDATION GATE (operation 'dynamic', before ANY backend call): the
 *      requested service + entity set MUST exist in the index; filter/select
 *      field names MUST be real filterable/selectable properties; key fields
 *      MUST match the entity set's declared keys. Any violation throws a
 *      CatalogError whose message lists the valid options — the executor turns
 *      that into an A2A `input-required` state WITHOUT touching the backend.
 *
 * This module performs NO I/O against SAP. It only reads the local index file.
 */

const fs = require("fs");
const path = require("path");

const INDEX_PATH =
  process.env.CATALOG_INDEX_PATH || path.join(__dirname, "catalog-index.json");

let cache = null;

/** Error carrying a user-facing message that lists valid options. */
class CatalogError extends Error {
  constructor(message) {
    super(message);
    this.name = "CatalogError";
  }
}

/**
 * Load + cache the capability index. Throws a clear CatalogError if the file is
 * missing or malformed (it is a generated build artifact — run `npm run gen:all`).
 */
function loadIndex() {
  if (cache) return cache;
  if (!fs.existsSync(INDEX_PATH)) {
    throw new CatalogError(
      "Capability index not found at " +
        INDEX_PATH +
        ". Generate it with `npm run gen:all` (fetch-metadata -> gen-catalog -> gen-skills)."
    );
  }
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(INDEX_PATH, "utf8"));
  } catch (e) {
    throw new CatalogError("Capability index at " + INDEX_PATH + " is not valid JSON: " + e.message);
  }
  if (!parsed || typeof parsed !== "object" || !parsed.services || typeof parsed.services !== "object") {
    throw new CatalogError("Capability index at " + INDEX_PATH + " has no 'services' object.");
  }
  cache = parsed;
  return cache;
}

/** Test/regeneration hook: drop the in-memory cache. */
function _resetCache() {
  cache = null;
}

/* --------------------------------------------------------------------------
 * Lookups (throwing, with helpful "valid options" messages)
 * ------------------------------------------------------------------------ */

function serviceNames() {
  return Object.keys(loadIndex().services).sort();
}

function getService(serviceName) {
  const idx = loadIndex();
  const svc = serviceName && idx.services[serviceName];
  if (!svc) {
    throw new CatalogError(
      `Unknown service '${serviceName}'. Valid services: ${serviceNames().join(", ")}.`
    );
  }
  return svc;
}

function entitySetNames(serviceName) {
  const svc = getService(serviceName);
  return Object.keys(svc.entitySets || {}).sort();
}

function getEntitySet(serviceName, entitySetName) {
  const svc = getService(serviceName);
  const set = entitySetName && svc.entitySets && svc.entitySets[entitySetName];
  if (!set) {
    throw new CatalogError(
      `Unknown entity set '${entitySetName}' in service '${serviceName}'. ` +
        `Valid entity sets: ${entitySetNames(serviceName).join(", ")}.`
    );
  }
  return set;
}

/** Property names of an entity set that are filterable. */
function filterableFields(set) {
  return Object.entries(set.properties || {})
    .filter(([, p]) => p.filterable)
    .map(([name]) => name);
}

/** All selectable property names (everything the index knows about the set). */
function selectableFields(set) {
  return Object.keys(set.properties || {});
}

/* --------------------------------------------------------------------------
 * VIEWS — operation 'catalog' (LOCAL, no backend call)
 * ------------------------------------------------------------------------ */

function listServices(domainFilter) {
  const idx = loadIndex();
  const want = domainFilter ? String(domainFilter).toLowerCase().trim() : null;
  const services = Object.entries(idx.services)
    .map(([name, svc]) => ({
      service: name,
      domain: svc.domain || "",
      hub: svc.hub || "",
      namespace: svc.namespace || "sap",
      entitySetCount: Object.keys(svc.entitySets || {}).length,
    }))
    .filter((s) => !want || s.domain.toLowerCase().includes(want))
    .sort((a, b) => a.service.localeCompare(b.service));
  return {
    view: "listServices",
    filteredByDomain: want || null,
    count: services.length,
    services,
    hint:
      "Call describeService(service) to see a service's entity sets, then " +
      "describeEntitySet(service, entitySet) to see exact field names before " +
      "calling searchEntitySet or getByKey.",
  };
}

function describeService(serviceName) {
  const svc = getService(serviceName);
  const entitySets = Object.entries(svc.entitySets || {})
    .map(([name, set]) => ({
      entitySet: name,
      entityType: set.entityType || "",
      role: set.role || "",
      keys: set.keys || [],
      requiresFilter: Boolean(set.requiresFilter),
      propertyCount: Object.keys(set.properties || {}).length,
      filterableCount: filterableFields(set).length,
    }))
    .sort((a, b) => a.entitySet.localeCompare(b.entitySet));
  return {
    view: "describeService",
    service: serviceName,
    domain: svc.domain || "",
    hub: svc.hub || "",
    namespace: svc.namespace || "sap",
    entitySetCount: entitySets.length,
    entitySets,
    hint:
      "Call describeEntitySet(service, entitySet) to see keys and " +
      "filterable/selectable properties with their types.",
  };
}

function describeEntitySet(serviceName, entitySetName) {
  const set = getEntitySet(serviceName, entitySetName);
  const properties = Object.entries(set.properties || {})
    .map(([name, p]) => ({
      name,
      label: p.label || "",
      type: p.type || "Edm.String",
      maxLength: p.maxLength,
      key: Boolean(p.key),
      filterable: Boolean(p.filterable),
      sortable: Boolean(p.sortable),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
  return {
    view: "describeEntitySet",
    service: serviceName,
    entitySet: entitySetName,
    entityType: set.entityType || "",
    namespace: getService(serviceName).namespace || "sap",
    keys: set.keys || [],
    requiresFilter: Boolean(set.requiresFilter),
    properties,
    hint:
      "Use these exact field names. searchEntitySet accepts a structured " +
      "filter [{field, op(eq/ne/gt/ge/lt/le), value}] over filterable fields; " +
      "getByKey needs the key field(s): " + (set.keys || []).join(", ") + ".",
  };
}

/** Dispatch a catalog view by backend.view + resolved params. */
function runView(view, { service, entitySet, domain } = {}) {
  switch (view) {
    case "listServices":
      return listServices(domain);
    case "describeService":
      return describeService(service);
    case "describeEntitySet":
      return describeEntitySet(service, entitySet);
    default:
      throw new CatalogError(
        `Unknown catalog view '${view}'. Valid views: listServices, describeService, describeEntitySet.`
      );
  }
}

/* --------------------------------------------------------------------------
 * VALIDATION GATE — operation 'dynamic' (runs BEFORE any backend call)
 * ------------------------------------------------------------------------ */

/**
 * Validate a structured filter against an entity set. Returns typed conditions
 * [{field, op, value, edmType}] ready for URL building. Throws CatalogError
 * (listing valid fields) on any unknown/non-filterable field.
 */
function validateFilter(set, conditions) {
  if (!conditions || conditions.length === 0) return [];
  const props = set.properties || {};
  const filterable = filterableFields(set);
  const out = [];
  for (const cond of conditions) {
    const prop = props[cond.field];
    if (!prop) {
      throw new CatalogError(
        `Filter field '${cond.field}' does not exist on this entity set. ` +
          `Filterable fields: ${filterable.join(", ")}.`
      );
    }
    if (!prop.filterable) {
      throw new CatalogError(
        `Filter field '${cond.field}' is not filterable. ` +
          `Filterable fields: ${filterable.join(", ")}.`
      );
    }
    out.push({ field: cond.field, op: cond.op, value: cond.value, edmType: prop.type || "Edm.String" });
  }
  return out;
}

/**
 * Validate a caller-supplied $select list against an entity set. Returns the
 * validated field array. Throws CatalogError on any unknown field.
 */
function validateSelect(set, fields) {
  if (!fields || fields.length === 0) return [];
  const selectable = new Set(selectableFields(set));
  for (const f of fields) {
    if (!selectable.has(f)) {
      throw new CatalogError(
        `Select field '${f}' does not exist on this entity set. ` +
          `Selectable fields: ${[...selectable].join(", ")}.`
      );
    }
  }
  return fields.slice();
}

/**
 * Validate a runtime key against an entity set's declared keys and return an
 * ordered array [{field, value, edmType}] following the index key order.
 *
 * @param {Object} set        entity set from the index
 * @param {*} keyValue        scalar (single-field key) or {field: value} object
 */
function validateKey(set, keyValue) {
  const keys = set.keys || [];
  if (keys.length === 0) {
    throw new CatalogError("This entity set has no declared key; getByKey is not possible.");
  }
  const props = set.properties || {};
  const typeOf = (field) => (props[field] && props[field].type) || "Edm.String";

  // Scalar shorthand only allowed for single-field keys.
  if (keyValue === null || typeof keyValue !== "object") {
    if (keys.length !== 1) {
      throw new CatalogError(
        `This entity set has a composite key (${keys.join(", ")}). Supply an object ` +
          `{ ${keys.map((k) => `${k}: value`).join(", ")} }.`
      );
    }
    return [{ field: keys[0], value: keyValue, edmType: typeOf(keys[0]) }];
  }

  // Object form: every declared key must be present; no extra fields allowed.
  const supplied = Object.keys(keyValue);
  const missing = keys.filter((k) => !(k in keyValue));
  if (missing.length) {
    throw new CatalogError(
      `Missing key field(s): ${missing.join(", ")}. This entity set's key is: ${keys.join(", ")}.`
    );
  }
  const extra = supplied.filter((k) => !keys.includes(k));
  if (extra.length) {
    throw new CatalogError(
      `Unknown key field(s): ${extra.join(", ")}. This entity set's key is: ${keys.join(", ")}.`
    );
  }
  return keys.map((k) => ({ field: k, value: keyValue[k], edmType: typeOf(k) }));
}

/**
 * Derive a sensible, narrow default $select for an entity set when the caller
 * doesn't pass one: keys first, then up to `limit` other selectable fields.
 */
function defaultSelect(set, limit = 12) {
  const keys = set.keys || [];
  const rest = selectableFields(set).filter((f) => !keys.includes(f));
  return [...keys, ...rest].slice(0, Math.max(keys.length, limit));
}

module.exports = {
  CatalogError,
  INDEX_PATH,
  loadIndex,
  _resetCache,
  serviceNames,
  getService,
  entitySetNames,
  getEntitySet,
  filterableFields,
  selectableFields,
  listServices,
  describeService,
  describeEntitySet,
  runView,
  validateFilter,
  validateSelect,
  validateKey,
  defaultSelect,
};
