"use strict";

/**
 * gen-skills.js — STEP 3 of the generation pipeline.
 *
 * Reads the curated catalog (reference/catalog.curated.json from gen-catalog.js)
 * and emits TWO kinds of generated artifacts:
 *
 *   1. srv/a2a/catalog-index.json
 *      The capability index the executor's `catalog` and `dynamic` operations
 *      consume at runtime. Nested-by-name for O(1) lookup:
 *        services[SVC].entitySets[SET].properties[PROP] = {type,label,...}
 *      This is the single source of truth for the runtime validation gate.
 *
 *   2. srv/a2a/skills/featured-*.yaml
 *      A small curated FEATURED subset of concrete STATIC skills (normal
 *      getByKey/list — NO engine change) for marquee entities, so Copilot Studio
 *      has ready, copy-pasteable examples. Keys and $select fields are taken
 *      straight from the curated catalog, so they are guaranteed real.
 *
 * Generated files carry a `__generated` marker / header comment and are fully
 * idempotent. The hand-written meta-skills (listServices/describeService/
 * describeEntitySet/searchEntitySet/getByKey) are NOT generated here.
 *
 * Usage (Windows PowerShell):
 *   node scripts\gen-skills.js
 */

const fs = require("fs");
const path = require("path");
const yaml = require("js-yaml");

const ROOT = path.join(__dirname, "..");
const REF_DIR = path.join(ROOT, "reference");
const CURATED_IN = path.join(REF_DIR, "catalog.curated.json");
const INDEX_OUT = path.join(ROOT, "srv", "a2a", "catalog-index.json");
const SKILLS_DIR = path.join(ROOT, "srv", "a2a", "skills");

const GENERATOR = "scripts/gen-skills.js";
const GEN_HEADER =
  "# GENERATED by " +
  GENERATOR +
  " — do not edit by hand.\n" +
  "# Re-run `npm run gen:skills` to regenerate. Hand-written meta-skills live\n" +
  "# alongside these files and are NOT touched by the generator.\n";

/* -------------------------------------------------------------------------- */
/* Capability index                                                           */
/* -------------------------------------------------------------------------- */

function buildIndex(catalog) {
  const services = {};
  for (const svc of Object.values(catalog.services)) {
    const entitySets = {};
    for (const es of svc.entitySets) {
      const properties = {};
      for (const p of es.properties) {
        properties[p.name] = {
          type: p.type,
          label: p.label || "",
          maxLength: p.maxLength,
          key: Boolean(p.key),
          filterable: Boolean(p.filterable),
          sortable: Boolean(p.sortable),
        };
      }
      entitySets[es.name] = {
        entityType: es.entityType,
        role: es.role,
        requiresFilter: Boolean(es.requiresFilter),
        keys: es.keys.slice(),
        properties,
      };
    }
    services[svc.service] = {
      domain: svc.domain,
      hub: svc.hub,
      namespace: svc.namespace || "sap",
      entitySets,
    };
  }
  return {
    __generated: true,
    generator: GENERATOR,
    generatedAt: new Date().toISOString(),
    sourceCounts: catalog.counts,
    services,
  };
}

/* -------------------------------------------------------------------------- */
/* Featured static skills                                                     */
/* -------------------------------------------------------------------------- */

// Marquee entities to feature. Each becomes a getByKey + a list skill. These are
// validated against the curated catalog at generation time so keys/fields are
// always real; if an entity set is missing from the curated catalog it is
// skipped with a warning (keeps generation robust to snapshot changes).
const FEATURED = [
  {
    service: "API_BUSINESS_PARTNER",
    entitySet: "A_BusinessPartner",
    label: "Business Partner",
    slug: "business-partner",
    domain: "master-data",
    tags: ["business-partner", "master-data", "customer", "supplier"],
  },
  {
    service: "API_SALES_ORDER_SRV",
    entitySet: "A_SalesOrder",
    label: "Sales Order",
    slug: "sales-order",
    domain: "sales",
    tags: ["sales-order", "sales", "order"],
  },
  {
    service: "API_PRODUCT_SRV",
    entitySet: "A_Product",
    label: "Product",
    slug: "product",
    domain: "master-data",
    tags: ["product", "material", "master-data"],
  },
  {
    service: "API_PURCHASEORDER_PROCESS_SRV",
    entitySet: "A_PurchaseOrder",
    label: "Purchase Order",
    slug: "purchase-order",
    domain: "procurement",
    tags: ["purchase-order", "procurement", "order"],
  },
];

const SELECT_LIMIT = 10;

function pickSelect(es) {
  const keys = es.keys.slice();
  const rest = es.properties
    .map((p) => p.name)
    .filter((n) => !keys.includes(n));
  return keys.concat(rest).slice(0, SELECT_LIMIT);
}

function camelize(field) {
  return field.charAt(0).toLowerCase() + field.slice(1);
}

function buildGetByKeySkill(feature, es) {
  if (es.keys.length !== 1) return null; // featured getByKey targets single-key sets
  const keyField = es.keys[0];
  const keyParam = camelize(keyField);
  return {
    id: "featured-" + feature.slug + "-get",
    name: "Get " + feature.label + " by key",
    description:
      "Read ONE " +
      feature.label +
      " document from " +
      feature.service +
      "/" +
      feature.entitySet +
      " by its key field `" +
      keyField +
      "`. Returns a narrow, fixed set of fields. This is a curated example of the STATIC getByKey pattern; for arbitrary services/entity sets use the generic getByKey meta-skill instead.",
    domain: feature.domain,
    tags: feature.tags.concat(["get-by-key", "featured"]),
    examples: [
      "Get " + feature.label.toLowerCase() + " 100000",
      "Show me " + feature.label.toLowerCase() + " with " + keyField + " 4711",
    ],
    params: [
      {
        name: keyParam,
        type: "string",
        required: true,
        description: keyField + " key value of the " + feature.label + ".",
      },
    ],
    backend: {
      service: feature.service,
      namespace: es.namespace || "sap",
      entitySet: feature.entitySet,
      operation: "getByKey",
      key: [{ field: keyField, param: keyParam }],
      select: pickSelect(es),
    },
  };
}

function buildListSkill(feature, es) {
  return {
    id: "featured-" + feature.slug + "-list",
    name: "List " + feature.label + "s",
    description:
      "List " +
      feature.label +
      " records from " +
      feature.service +
      "/" +
      feature.entitySet +
      " (first page, $top-capped). Returns a narrow, fixed set of fields. This is a curated example of the STATIC list pattern; for arbitrary services/entity sets or structured filters use the generic searchEntitySet meta-skill instead.",
    domain: feature.domain,
    tags: feature.tags.concat(["list", "featured"]),
    examples: [
      "List " + feature.label.toLowerCase() + "s",
      "Show the first 10 " + feature.label.toLowerCase() + "s",
    ],
    params: [
      {
        name: "top",
        type: "integer",
        required: false,
        min: 1,
        max: 100,
        default: 20,
        description: "Maximum number of rows to return (1-100).",
      },
    ],
    backend: {
      service: feature.service,
      namespace: es.namespace || "sap",
      entitySet: feature.entitySet,
      operation: "list",
      select: pickSelect(es),
      top: { param: "top", default: 20, max: 100 },
    },
  };
}

function dumpSkill(skill) {
  const body = yaml.dump(skill, { lineWidth: 100, noRefs: true });
  return GEN_HEADER + body;
}

/* -------------------------------------------------------------------------- */

function loadCurated() {
  if (!fs.existsSync(CURATED_IN)) {
    throw new Error(
      "Curated catalog not found at " +
        CURATED_IN +
        ". Run `npm run gen:catalog` first."
    );
  }
  return JSON.parse(fs.readFileSync(CURATED_IN, "utf8"));
}

function main() {
  const catalog = loadCurated();

  // 1. capability index
  const index = buildIndex(catalog);
  fs.mkdirSync(path.dirname(INDEX_OUT), { recursive: true });
  fs.writeFileSync(INDEX_OUT, JSON.stringify(index, null, 2), "utf8");

  const svcCount = Object.keys(index.services).length;
  let esCount = 0;
  for (const s of Object.values(index.services)) esCount += Object.keys(s.entitySets).length;

  process.stdout.write("gen-skills: wrote capability index\n");
  process.stdout.write("  " + INDEX_OUT + "\n");
  process.stdout.write("  services: " + svcCount + ", entity sets: " + esCount + "\n");

  // 2. featured static skills
  fs.mkdirSync(SKILLS_DIR, { recursive: true });

  // Clean previously generated featured-*.yaml so removals are idempotent.
  for (const f of fs.readdirSync(SKILLS_DIR)) {
    if (/^featured-.*\.yaml$/.test(f)) fs.unlinkSync(path.join(SKILLS_DIR, f));
  }

  const written = [];
  for (const feature of FEATURED) {
    const svc = catalog.services[feature.service];
    if (!svc) {
      process.stderr.write("  ! service not in curated catalog: " + feature.service + "\n");
      continue;
    }
    const esRaw = svc.entitySets.find((e) => e.name === feature.entitySet);
    if (!esRaw) {
      process.stderr.write(
        "  ! entity set not found: " + feature.service + "/" + feature.entitySet + "\n"
      );
      continue;
    }
    const es = Object.assign({ namespace: svc.namespace }, esRaw);

    const get = buildGetByKeySkill(feature, es);
    if (get) {
      const file = path.join(SKILLS_DIR, get.id + ".yaml");
      fs.writeFileSync(file, dumpSkill(get), "utf8");
      written.push(get.id);
    }
    const list = buildListSkill(feature, es);
    const listFile = path.join(SKILLS_DIR, list.id + ".yaml");
    fs.writeFileSync(listFile, dumpSkill(list), "utf8");
    written.push(list.id);
  }

  process.stdout.write("gen-skills: wrote " + written.length + " featured skills\n");
  for (const id of written) process.stdout.write("  - " + id + "\n");
  process.stdout.write("\nNext: npm run validate:skills\n");
}

main();
